# -*- coding: utf-8 -*-
"""breastCancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KjN53RmbmYH53k7splH_Av3345sX-_2K
"""

import numpy as np

data = np.loadtxt('./data.csv',delimiter = ',', dtype=np.float32)
# x - y + z - w 식

xdata = data[:,1:-1]
tdata = data[:,0:1]

print(xdata.shape, tdata.shape)

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(xdata,tdata,test_size = 0.2, random_state = 1)

xVal, xTest, yVal, yTest = train_test_split(xTest,yTest,test_size = 0.5, random_state = 1)

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam

model = Sequential()

model.add(Dense(32,input_shape=(29,), activation = 'tanh'))
model.add(Dense(64,activation = 'tanh'))
model.add(Dropout(0.5))
model.add(Dense(64,activation = 'tanh'))
model.add(Dense(32,activation = 'relu'))
model.add(Dropout(0.3))
model.add(Dense(32,activation = 'tanh'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer = 'Adam',metrics=['accuracy'])
model.summary()

trained_model = model.fit(xTrain, yTrain,
          batch_size=32,
          epochs=5000,
          validation_data=(xVal, yVal),
          shuffle=True)

res = model.evaluate(xTest, yTest)

print(res)



